---
title: "Supplemental Figures"
author: "Kevin Thomas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmarkdown::github_document:
    toc: true
    toc_depth: 3
    # toc_float: true
---

```{css, echo=FALSE}
    body .main-container {
      max-width: 1500px !important;
      width: 1500px !important;
    }
    body {
      max-width: 1500px !important;
    }
```

```{r setup, include=FALSE}
# Set options
options(width = 1200)
knitr::opts_chunk$set(echo = TRUE, fig.width = 12, fig.height = 12)

# Attach libraries
source("../R/packages.R")

# Define custom functions
source("../R/functions.R")

# Set plot theme
theme_set(cowplot::theme_cowplot())

library(scales)
log10p <- scales::trans_new(
  name = "log10p",
  transform = function(x) log10(x+1),
  inverse = function(x) 10^x-1
)
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

# Import pre_qc, gem_classification, and final seurat object
pre_qc <- readRDS(file = "../data/pre_qc.RDS")
gem_classification <- readRDS(file = "../data/gem_classification.RDS")
sc <- readRDS(file = "../data/final_seurat.RDS")
primary_species_prefix = "GRCh38_"
secondary_species_prefix = "mm10___"
```

## S10A
### Setting graphical cutoffs
```{r Set human and mouse cutoffs graphically}
# Set mouse cutoffs
mouse_cutoffs <- list(
  s1a = data.frame(
    x = c(0, 0, 25, 25, 7, 7),
    y = c(400, 58100, 58100, 11000, 900, 400)
  ),
  s1b = data.frame(
    x = c(0, 0, 25, 25, 7, 7),
    y = c(400, 58100, 58100, 11000, 900, 400)
  ),
  s2a = data.frame(
    x = c(0, 0, 25, 25, 7, 7),
    y = c(400, 58100, 58100, 11000, 900, 400)
  ),
  s2b = data.frame(
    x = c(0, 0, 30, 30, 7, 7),
    y = c(400, 58100, 58100, 11000, 900, 400)
  ),
  s3a = data.frame(
    x = c(0, 0, 20, 20, 10, 10),
    y = c(50, 5500, 5500, 1200, 200, 50)
  ),
  s3b = data.frame(
    x = c(0, 0, 700, 700, 40, 40),
    y = c(120, 40000, 40000, 8800, 300, 120)
  ),
  s4a = data.frame(
    x = c(0, 0, 80, 80, 10, 4),
    y = c(300, 14000, 14000, 5000, 1000, 300)
  ),
  s4b = data.frame(
    x = c(0, 0, 100, 100, 15, 10),
    y = c(200, 20000, 20000, 5000, 400, 200)
  ),
  s5a = data.frame(
    x = c(0, 0, 100, 100, 20, 20),
    y = c(100, 15000, 15000, 3000, 300, 100)
  ),
  s5b = data.frame(
    x = c(0, 0, 100, 100, 20),
    y = c(300, 15000, 15000, 3000, 300)
  )
) %>%
  bind_rows(.id = "run")

# Set human cutoffs
human_cutoffs <- list(
  s1a = data.frame(
    x = c(100, 10000, 10000, 100),
    y = c(70, 70, 0, 0)
  ),
  s1b = data.frame(
    x = c(100, 10000, 11000, 100),
    y = c(70, 70, 0, 0)
  ),
  s2a = data.frame(
    x = c(100, 10000, 10000, 100),
    y = c(80, 80, 0, 0)
  ),
  s2b = data.frame(
    x = c(100, 10000, 10000, 100),
    y = c(80, 80, 0, 0)
  ),
  s3a = data.frame(
    x = c(15, 10000, 10000, 15),
    y = c(150, 150, 0, 0)
  ),
  s3b = data.frame(
    x = c(50, 10000, 10000, 50),
    y = c(150, 150, 0, 0)
  ),
  s4a = data.frame(
    x = c(20, 10000, 10000, 20),
    y = c(225, 225, 0, 0)
  ),
  s4b = data.frame(
    x = c(50, 100, 10000, 10000, 50),
    y = c(150, 300, 300, 0, 0)
  ),
  s5a = data.frame(
    x = c(25, 10000, 10000, 25),
    y = c(150, 150, 0, 0)
  ),
  s5b = data.frame(
    x = c(30, 10000, 10000, 30),
    y = c(150, 150, 0, 0)
  )
) %>%
  bind_rows(.id = "run")
```

### Plotting
```{r S10A, fig.height=7, fig.width=12}
plots <- map(
  .x = unique(gem_classification$run),
  .f = function(r) {
    df <- gem_classification %>%
      filter(run == r)
    mc <- mouse_cutoffs %>%
      filter(run == r)
    hc <- human_cutoffs %>%
      filter(run == r)
    cutoffs <- bind_rows(
      `names<-`(
        x = list(mc, hc),
        value = c(str_remove_all(secondary_species_prefix, "_"), str_remove_all(primary_species_prefix, "_"))
      ),
      .id = "Species"
    )
    
    gg <- ggplot(
      data = df,
      mapping = aes(
        x = eval(parse(text=paste0("`", str_remove_all(primary_species_prefix, "_"), "_counts`"))),
        y = eval(parse(text=paste0("`", str_remove_all(secondary_species_prefix, "_"), "_counts`"))),
      )
    ) +
    geom_point(
      size = 0.2,
      shape = 16,
    ) +
    stat_density_2d(aes(fill = ..level..), geom = "polygon", contour_var = "ndensity") +
    scale_fill_viridis(option = "magma") +
    geom_polygon(aes(x, y, group = Species, color = Species), data = cutoffs, fill = NA) +
    scale_color_manual(
      values = `names<-`(
        x = c("#00a1df", "#58a532"),
        value = c(str_remove_all(secondary_species_prefix, "_"), str_remove_all(primary_species_prefix, "_"))
      ),
      guide = guide_legend(title = "Species call", override.aes = list(alpha = 0))
    ) +
    scale_x_continuous(
      trans = log10p,
      breaks = map_int(0:4, ~int(10^.x)),
      labels = scales::trans_format("log10", scales::math_format(10^.x)),
      limits = c(
        min(
          c(
            eval(parse(text=paste0("gem_classification$", str_remove_all(primary_species_prefix, "_"), "_counts"))),
            human_cutoffs$x
          )
        ),
        max(
          c(
            eval(parse(text=paste0("gem_classification$", str_remove_all(primary_species_prefix, "_"), "_counts"))),
            human_cutoffs$x
          )
        )
      )
    ) +
    scale_y_continuous(
      trans = log10p,
      breaks = map_int(0:4, ~int(10^.x)),
      labels = scales::trans_format("log10", scales::math_format(10^.x)),
      limits = c(
        min(
          c(
            eval(parse(text=paste0("gem_classification$", str_remove_all(secondary_species_prefix, "_"), "_counts"))),
            mouse_cutoffs$y
          )
        ),
        max(
          c(
            eval(parse(text=paste0("gem_classification$", str_remove_all(secondary_species_prefix, "_"), "_counts"))),
            mouse_cutoffs$y
          )
        )
      )
    ) +
    facet_wrap(~run) +
    labs(
      x = paste0(str_remove_all(primary_species_prefix, "_"), "_counts"),
      y = paste0(str_remove_all(secondary_species_prefix, "_"), "_counts"),
      fill = "Scaled density"
    ) +
    theme(
      legend.position = "hidden",
      strip.background = element_blank(),
      strip.text = element_text(face = "bold"),
    ) +
    coord_fixed()
    
    return (gg)
  }
)

legend <- get_legend(plots[[1]] + theme(legend.position = c(0.5,0.5), legend.direction = "horizontal", legend.justification = "center") + guides(fill = guide_colorbar(barwidth = 20)))

plot_grid(
  plots[[1]],
  plots[[2]],
  plots[[3]],
  plots[[4]],
  plots[[5]],
  plots[[6]],
  plots[[7]],
  plots[[8]],
  plots[[9]],
  plots[[10]],
  NULL,
  NULL,
  legend,
  ncol = 5,
  rel_heights = c(1,1,0.5)
)
```

## S10B
```{r 10B, fig.height = 25, fig.width=12}
# Make heatmaps showing assignments by HTODemux (Seurat)
heatmaps1 <- map(
  .x = str_sort(unique(pre_qc$run)),
  .f = function (i) {
    # Subset pre_qc object and scale the HTO data
    object <- subset(
        x = pre_qc,
        cells = gem_classification[
          which(x = gem_classification$call == str_remove_all(primary_species_prefix, "_") & gem_classification$run == i),
        ] %>%
          (function(x) paste0(x$run, "_", x$cells))
    ) %>%
      subset(x = ., cells = sample(x = colnames(x = .), size = 5000)) %>%
      ScaleData(object = ., assay = "HTO", verbose = FALSE)
    
    # Define singlets and doublets
    singlets <- which(x = object$HTO_classification.global == "Singlet")
    doublets <- which(x = object$HTO_classification.global == "Doublet")
    
    # Set levels for the HTO classification and hash IDs
    object$HTO_classification.global <- factor(
      x = object$HTO_classification,
      levels = c(
        sort(unique(object$HTO_classification[singlets])),
        sort(unique(object$HTO_classification[doublets])),
        "Negative"
      )
    )
    object$hash.ID <- factor(
      x = object$hash.ID,
      levels = c(
        sort(unique(object$HTO_classification[singlets])),
        "Doublet",
        "Negative"
      )
    )
    
    # Putting hash groups in correct order
    plot.order <- factor(
      x = object$HTO_classification,
      levels = c(
        sort(unique(object$HTO_classification[singlets])),
        sort(unique(object$HTO_classification[doublets])),
        "Negative"
      )
    ) %>%
      sort() %>%
      names()
    
    # Make the plot
    gg <- DoHeatmap(
      object = object,
      assay = "HTO",
      features = rownames(object[["HTO"]]),
      cells = plot.order,
      group.by = "hash.ID",
      group.bar = TRUE,
      group.colors = gg_color_hue(n = 7)[c(1:length(unique(object$hash.ID[singlets])),6:7)],
      disp.min = -2.5,
      disp.max = 2.5,
      size = 3
    ) +
      labs(title = i) +
      theme(
        plot.title = element_text(size = 12),
        legend.position = "hidden"
      )
    return(gg)
  }
)

# Make heatmaps showing assignments by DeMULTIplex
heatmaps2 <- map(
  .x = str_sort(unique(pre_qc$run)),
  .f = function (i) {
    # Subset pre_qc object and scale the HTO data
    object <- subset(
        x = pre_qc,
        cells = gem_classification[
          which(x = gem_classification$call == str_remove_all(primary_species_prefix, "_") & gem_classification$run == i),
        ] %>%
          (function(x) paste0(x$run, "_", x$cells))
    ) %>%
      subset(x = ., cells = sample(x = colnames(x = .), size = 5000)) %>%
      ScaleData(object = ., assay = "HTO", verbose = FALSE)
    
    # Define singlets and doublets
    singlets <- which(x = object$deMULTIplex.calls.rescued %nin% c("Negative", "Doublet"))
    doublets <- which(x = object$deMULTIplex.calls.rescued == "Doublet")
    
    # Set levels for the HTO classification and hash IDs
    object$deMULTIplex.calls.rescued <- factor(
      x = object$deMULTIplex.calls.rescued,
      levels = c(
        sort(unique(object$deMULTIplex.calls.rescued)[unique(object$deMULTIplex.calls.rescued) %nin% c("Negative", "Doublet")]),
        "Doublet",
        "Negative"
      )
    )
    
    # Make the plot
    gg <- DoHeatmap(
      object = object,
      assay = "HTO",
      features = rownames(object[["HTO"]]),
      group.by = "deMULTIplex.calls.rescued",
      group.bar = TRUE,
      group.colors = gg_color_hue(n = 7)[c(1:length(unique(object$deMULTIplex.calls.rescued[singlets])),6:7)],
      disp.min = -2.5,
      disp.max = 2.5,
      size = 3
    ) +
      labs(title = i) +
      theme(
        plot.title = element_text(size = 12),
        legend.position = "hidden"
      )
    return(gg)
  }
)

# Make a common legend
legend <- get_legend(heatmaps1[[10]] + theme(legend.position = c(0.5,0.75), legend.direction = "horizontal") + guides(fill = guide_colorbar(barwidth = 20)))

# Plot grid
plot_grid(
  heatmaps1[[1]],
  heatmaps2[[1]],
  heatmaps1[[2]],
  heatmaps2[[2]],
  heatmaps1[[3]],
  heatmaps2[[3]],
  heatmaps1[[4]],
  heatmaps2[[4]],
  heatmaps1[[5]],
  heatmaps2[[5]],
  heatmaps1[[6]],
  heatmaps2[[6]],
  heatmaps1[[7]],
  heatmaps2[[7]],
  heatmaps1[[8]],
  heatmaps2[[8]],
  heatmaps1[[9]],
  heatmaps2[[9]],
  heatmaps1[[10]],
  heatmaps2[[10]],
  legend,
  ncol = 2)
```

## S10C
```{r S10C, fig.height = 25, fig.width=12}
map(
  .x = str_sort(unique(pre_qc$run)),
  .f = function(i) {
    # Subset object by run
    obj <- pre_qc %>%
      subset(
        cells = gem_classification[
          which(x = gem_classification$call == str_remove_all(primary_species_prefix, "_") & gem_classification$run == i),
        ] %>%
          (function(x) paste0(x$run, "_", x$cells))
      ) %>%
      PurgeXenoGenes(
        object = .,
        primary_species_prefix = str_replace_all(primary_species_prefix, "_", "-"),
        secondary_species_prefix = str_replace_all(secondary_species_prefix, "_", "-")
      ) %>%
      # Only singlets
      subset(`final.HTO.ID` %nin% c("Doublet", "Negative")) %>%
      # Percent mito and hemoglobin
      PercentageFeatureSet(
        object = .,
        pattern = "^MT-",
        col.name = "percent_mt"
      ) %>%
      PercentageFeatureSet(
        object = .,
        pattern = "^HB[ABDEGMQZ].?$",
        col.name = "percent_hemo"
      )
    
    # Make plots
    gg <- FetchData(
      object = obj,
      vars = c("nFeature_RNA", "percent_mt", "percent_hemo", "nCount_RNA")
    ) %>%
      dplyr::rename(nGenes = nFeature_RNA) %>%
      # as.data.frame() %>%
      ggplot(data = ., aes(x = nGenes, y = percent_mt)) +
      geom_point(size = 0.2, shape = 16, show.legend = FALSE) +
      stat_density_2d(aes(fill = ..level..), geom = "polygon", contour_var = "density", show.legend = FALSE) +
      scale_fill_viridis(option = "magma") +
      geom_hline(yintercept = 25, col = "red") +
      geom_vline(xintercept = 40, col = "red") +
      scale_x_continuous(
        trans = log10p,
        breaks = map_int(0:5, ~int(10^.x)),
        labels = scales::trans_format("log10", scales::math_format(10^.x)),
        limits = c(min(pre_qc$nFeature_RNA), max(pre_qc$nFeature_RNA))
      ) +
      scale_y_continuous(limits = c(0,57), breaks = c(10,20,30,40,50)) +
      labs(title = i) +
      theme(
        plot.title = element_text(hjust = 0.5, size = 12)
      )
    return(gg)
  }
) %>% plot_grid(plotlist = ., ncol = 2)
```

## S11A-B
```{r S11, fig.height=7.5, fig.width=8}
# PCA dimensions with and without Harmony correction for batch
FetchData(
  object = sc,
  vars = c(
    "run",
    paste0(c(rep("PC_",2), rep("harmony_",2), rep("citePCA_",2), rep("harmonycite_",2)), rep(1:2, 4))
  )
) %>%
  pivot_longer(
    cols = paste0(c("PC_", "harmony_", "citePCA_", "harmonycite_"), 1),
    names_to = "dim1",
    values_to = "value1"
  ) %>%
  pivot_longer(
    cols = paste0(c("PC_", "harmony_", "citePCA_", "harmonycite_"), 2),
    names_to = "dim2",
    values_to = "value2"
  ) %>%
  mutate(
    reduction = str_extract(dim1, "[^_]*") %>%
      factor(levels = c("PC", "harmony", "citePCA", "harmonycite")) %>%
      fct_recode(rnaPCA = "PC", rnaHarmony = "harmony", citePCA = "citePCA", citeHarmony = "harmonycite")
  ) %>%
  ggplot(aes(x = value1, y = value2, col = run)) +
  geom_point(size = 0.4) +
  facet_wrap(~reduction, scales = "free_x") +
  cowplot::theme_cowplot() +
  theme(strip.background = element_blank(), strip.text = element_text(face = "bold")) +
  labs(x = NULL, y = NULL, col = NULL)
```

## S12
```{r S12, fig.height=15, fig.width=26.7}
# Plot UMAP reductions for each patient
FetchData(
  object = sc,
  vars = c("ancestry", "classification", "clusters_annotated", "subject_id", "wnnUMAP_1", "wnnUMAP_2")
) %>%
  mutate(
    group = paste0(ancestry, " ", classification) %>%
      factor(levels = c("EA Control", "EA SLE INACT", "EA SLE ACT", "AA Control", "AA SLE INACT", "AA SLE ACT"))
  ) %>%
  ggplot(aes(x = wnnUMAP_1, y = wnnUMAP_2, col = clusters_annotated)) +
  geom_point(size = 0.4) +
  scale_color_manual(
    values = `names<-`(pals::cols25(n = length(levels(sc$clusters_annotated))), levels(sc$clusters_annotated))
  ) +
  facet_wrap(~group + subject_id, nrow = 5) +
  labs(x = NULL, y = NULL, col = NULL) +
  theme(
    panel.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    legend.key = element_blank()
  ) +
  coord_fixed()
```

## S13A
```{r S13A, fig.height=7.5, fig.width = 7.5}
# Plot total UMAP of object after QC
DimPlot(
  object = sc,
  reduction = "umap_wnn",
  dims = c(1,2),
  group.by = "coarse_cell_type",
  cols = `names<-`(pals::okabe(n = length(levels(sc$coarse_cell_type))), unique(sc$coarse_cell_type)),
  label = TRUE,
  label.size = 4
) +
  labs(title = NULL, x = NULL, y = NULL) + 
  NoLegend() +
  coord_fixed()
```

## S13B
```{r S13B, fig.height=3.75, fig.width = 7.5}
# CITE markers of coarse cell types
coarse_markers_cite <- c("CD19", "CD21", "CD38", "CD27", "CD34", "CD117", "CD1c", "HLA-DR", "CD11c", "CD14", "CD56", "CD16", "CD123", "CD4", "CD8a", "CD127")

# Bubbleplot
bubbleplot(
  object = sc,
  assay = "CITE",
  slot = "data",
  features_plot = coarse_markers_cite,
  preserve_feature_order = TRUE,
  grouping_var = "coarse_cell_type",
  filter_exp_pct_thresh = 1,
  avg_func = "median",
  do_return = TRUE
) +
  scale_size_continuous() +
  scale_color_distiller(palette = "Reds", direction = 1) +
  labs(title = NULL, x = NULL, y = NULL, col = "Scaled median expression", size = "Percent cells expressing") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```

## S13C
```{r S13C, fig.height=3.75, fig.width=7.5}
# Gene markers of coarse cell types
coarse_markers_genes <- c("CD74", "MS4A1", "JCHAIN", "MZB1", "ZNF385D", "SOX4", "HLA-DPB1", "FCER1A", "S100A8", "LYZ", "GNLY", "NKG7", "TCF4", "IRF7", "CD3D", "IL32")

bubbleplot(
  object = sc,
  assay = "SCT",
  slot = "data",
  features_plot = coarse_markers_genes,
  preserve_feature_order = TRUE,
  cluster_x = FALSE,
  grouping_var = "coarse_cell_type",
  filter_exp_pct_thresh = 0,
  avg_func = "mean",
  do_return = TRUE
) +
  scale_size_continuous() +
  scale_color_distiller(palette = "Blues", direction = 1) +
  labs(title = NULL, x = NULL, y = NULL, col = "Scaled median expression", size = "Percent cells expressing") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```

## S14
```{r S14, fig.height=10.3, fig.width=20}
# Global CITEseq heatmap
## Fetch data for all values and turn into matrix
mat <- FetchData(
  object = `DefaultAssay<-`(sc, value = "CITE"),
  vars = c("classification", "ancestry", "clusters_annotated", rownames(sc[["CITE"]])[rownames(sc[["CITE"]]) != "isotype-control"])
) %>%
  as_tibble(rownames = "cell") %>%
  group_by(
    ident = factor(
      x = paste0(get("clusters_annotated"), " ", get("ancestry"), " ", get("classification")),
      levels = expand.grid(
        c("EA Control", "EA SLE INACT", "EA SLE ACT", "AA Control", "AA SLE INACT", "AA SLE ACT"),
        levels(get("clusters_annotated"))
      ) %>%
        (function (x) {paste0(x$Var2, " ", x$Var1)})
    )
  ) %>%
  summarize_if(is.numeric, median) %>%
  as.data.frame() %>%
  column_to_rownames("ident") %>%
  t()

pheatmap::pheatmap(
  mat = mat,
  breaks = seq.int(-3,3,length.out = 100),
  scale = "row",
  cluster_col = F,
  # treeheight_row = 0,
  gaps_col = (1:ncol(mat))[(1:ncol(mat) %% 6) == 0],
  main = "All cell types"
)
```



```{r}
devtools::session_info()
```