reticulate::use_condaenv(condaenv = "reticulate", required = TRUE, conda = "/home/rstudio/conda/bin/conda")
library(Matrix)
library(SoupX)
library(ggrepel)
library(Matrix)
library(tibble)
library(formattable)
library(xml2)
library(glue)
library(deMULTIplex)
library(dsb)
library(BiocParallel)
library(cowplot)
library(drake)
library(ggforce)
# library(IRdisplay)
library(janitor)
library(kableExtra)
library(magrittr)
library(paletteer)
library(RColorBrewer)
library(tidyverse)
library(viridis)
library(data.table)
library(Seurat)
# library(SeuratWrappers)
library(harmony)
library(reticulate)
library(ReductionWrappers)
library(rsvd)
library(presto)
library(rlang)
library(ViolinEnsemble)
library(SeuratBubblePlot)
# library(schex)
library(SingleR)
library(scater)
library(BiocNeighbors)
library(lubridate)
library(furrr)
library(forcats)
library(ggrepel)
library(s2a)
library(scClustViz)
library(future.callr)